#!/usr/bin/bash
eval $(ssh-agent)
source ~/../usr/bin/source-ssh-agent # path might varied based on your system and brand
cd storage/downloads/logseq
git add -A
git commit -m "sync from android"
git push
